apiVersion: packaging.kubeclipper.io/v1alpha1
kind: OfflineResourceBuild
release: v1.8.0
architectures:
  - amd64
registries:
  package: ghcr.io/kubeclipper
  image: ghcr.io/kubeclipper
bootstrap:
  kubeclipperVersion: v1.8.0
  etcdVersion: 3.5.21
  caddyVersion: 2.10.2
  caddyUrlTemplate: https://github.com/caddyserver/caddy/releases/download/v${version}/caddy_${version}_linux_${arch}.tar.gz
  registry:
    bootstrapImage: registry:2
    binaryUrlTemplate: ""
resources:
  k8s:
    versions:
      - v1.36.1
    etcdVersion: 3.5.21
    helmVersion: 3.18.6
    kubeadmConfVersion: 0.16.2
    conntrack:
      source: build
      version: 1.4.9
      method: docker-source
  cri:
    containerd:
      versions:
        - 2.2.4
      runcVersion: 1.3.3
      crictlVersion: 1.35.0
  cni:
    calico:
      versions:
        - v3.31.5
      chartVersion: v3.31.5
      helmRepo: https://docs.tigera.io/calico/charts
addons:
  nvidia-dra-driver-gpu:
    enabled: false
    versions:
      - 25.8.0
    chartRepo: https://helm.ngc.nvidia.com/nvidia
    chartName: nvidia-dra-driver-gpu
    chartVersion: 25.8.0
  nvidia-gpu-operator:
    enabled: false
    versions:
      - v25.10.0
    chartRepo: https://helm.ngc.nvidia.com/nvidia
    chartName: gpu-operator
    chartVersion: 25.10.0
