#!/usr/bin/env bash

set -euo pipefail

images_lock=""
image_registry=""
tool=""
dry_run=false
components=()
versions=()
arches=()

usage() {
  cat <<'EOF'
Usage:
  push-runtime-images.sh --images-lock <file> --image-registry <prefix> [flags]

Flags:
  --images-lock <file>       TSV file generated by build-offline-resources.sh.
  --image-registry <prefix>  Target runtime image Registry, e.g. registry.local:5000.
  --tool <crane|skopeo>      Image copy tool. Default: auto-detect.
  --component <name>         Push only images for this resource component. Can be repeated.
  --version <version>        Push only images for this resource version. Can be repeated.
  --arch <arch>              Push only images for this architecture. Can be repeated.
  --dry-run                  Print copy commands without pushing.
  -h, --help                 Show this help.

Notes:
  The target image comes from images.lock. The open-packaging metadata generator
  strips the upstream registry host so install-time image names stay short:
  registry.k8s.io/pause:3.10 -> registry.local:5000/pause:3.10
  docker.io/calico/node:v3.31.5 -> registry.local:5000/calico/node:v3.31.5
  registry.k8s.io/coredns/coredns:v1.14.2 -> registry.local:5000/coredns:v1.14.2
  Standard OCI images are copied as-is. When an upstream image is a
  multi-architecture index, the target retains that index instead of replacing
  an already-published architecture with the next selected architecture.
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

need_value() {
  [[ $# -ge 2 && -n "$2" ]] || die "$1 requires a value"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  --images-lock) need_value "$@"; images_lock="$2"; shift 2 ;;
  --image-registry) need_value "$@"; image_registry="${2%/}"; shift 2 ;;
  --tool) need_value "$@"; tool="$2"; shift 2 ;;
  --component) need_value "$@"; components+=("$2"); shift 2 ;;
  --version) need_value "$@"; versions+=("$2"); shift 2 ;;
  --arch) need_value "$@"; arches+=("$2"); shift 2 ;;
  --dry-run) dry_run=true; shift ;;
  -h | --help) usage; exit 0 ;;
  *) die "unknown argument: $1" ;;
  esac
done

[[ -n "$images_lock" ]] || die "--images-lock is required"
[[ -f "$images_lock" ]] || die "images lock not found: $images_lock"
[[ -n "$image_registry" ]] || die "--image-registry is required"

detect_tool() {
  if [[ "$dry_run" == true && -z "$tool" ]]; then
    echo "crane"
    return
  fi
  if [[ -n "$tool" ]]; then
    command -v "$tool" >/dev/null 2>&1 || die "$tool is required"
    echo "$tool"
    return
  fi
  if command -v crane >/dev/null 2>&1; then
    echo "crane"
    return
  fi
  if command -v skopeo >/dev/null 2>&1; then
    echo "skopeo"
    return
  fi
  die "crane or skopeo is required"
}

copy_tool="$(detect_tool)"
published=0
copy_retries="${KC_IMAGE_COPY_RETRIES:-3}"
copy_retry_delay="${KC_IMAGE_COPY_RETRY_DELAY:-5}"

image_digest() {
  local ref=$1
  case "$copy_tool" in
  crane) crane digest "$ref" ;;
  skopeo) skopeo inspect --format '{{.Digest}}' "docker://$ref" ;;
  esac
}

component_filter() {
  local item=$1
  shift
  if [[ $# -eq 0 ]]; then
    return 0
  fi
  local wanted
  for wanted in "$@"; do
    [[ "$wanted" == "$item" ]] && return 0
  done
  return 1
}

target_image() {
  local source=$1
  local path="$source"
  local first="${path%%/*}"
  if [[ "$first" == *.* || "$first" == *:* || "$first" == "localhost" ]]; then
    path="${path#*/}"
  fi
  case "$source" in
  registry.k8s.io/coredns/coredns:*)
    path="coredns:${source##*:}"
    ;;
  esac
  echo "$image_registry/$path"
}

seen_targets="$(mktemp -t kc-runtime-images.XXXXXX)"
digest_error="$(mktemp -t kc-runtime-digest.XXXXXX)"
trap 'rm -f "$seen_targets" "$digest_error"' EXIT

{
  read -r _header
  while IFS=$'\t' read -r _resource _version arch source target; do
    [[ -n "${source:-}" ]] || continue
    component_filter "$_resource" "${components[@]}" || continue
    component_filter "$_version" "${versions[@]}" || continue
    component_filter "$arch" "${arches[@]}" || continue
    target="$(target_image "$source")"
    [[ -n "${arch:-}" ]] || die "missing architecture for image: $source"

    # An image list can contain the same source for multiple selected
    # architectures. Copying the native OCI index once preserves all of them.
    if grep -Fqx -- "$target" "$seen_targets"; then
      continue
    fi
    printf '%s\n' "$target" >> "$seen_targets"

    case "$copy_tool" in
    crane)
      cmd=(crane copy "$source" "$target")
      ;;
    skopeo)
      cmd=(skopeo copy --multi-arch all "docker://$source" "docker://$target")
      ;;
    *)
      die "unsupported tool: $copy_tool"
      ;;
    esac
    if [[ "$dry_run" == true ]]; then
      printf 'dry-run:'
      printf ' %q' "${cmd[@]}"
      printf '\n'
    else
      source_digest="$(image_digest "$source")" || die "cannot resolve source image digest: $source"
      if ! target_digest="$(image_digest "$target" 2>"$digest_error")"; then
        if grep -Eqi 'MANIFEST[_ ]UNKNOWN|NAME[_ ]UNKNOWN|404[[:space:]]+Not Found|status( code)?:?[[:space:]]*404|unexpected status.*404' "$digest_error"; then
          target_digest=""
        else
          die "cannot inspect target image $target: $(tr '\n' ' ' < "$digest_error")"
        fi
      fi
      if [[ -n "$target_digest" && "$source_digest" == "$target_digest" ]]; then
        echo "==> target image already matches source, skip: $target"
        published=$((published + 1))
        continue
      fi
      if [[ -n "$target_digest" ]]; then
        die "runtime image tag conflict: $target already points to $target_digest, refusing $source_digest"
      fi
      echo "==> ${cmd[*]}"
      ok=false
      for ((attempt = 1; attempt <= copy_retries; attempt++)); do
        if "${cmd[@]}"; then
          ok=true
          break
        fi
        if ((attempt < copy_retries)); then
          echo "copy failed, retrying in ${copy_retry_delay}s ($attempt/$copy_retries): $source" >&2
          sleep "$copy_retry_delay"
        fi
      done
      [[ "$ok" == true ]] || die "copy image failed after $copy_retries attempts: $source"
    fi
    published=$((published + 1))
  done
} < "$images_lock"

echo "processed $published runtime image(s)"
