#!/usr/bin/env bash

set -euo pipefail

images_lock=""
image_registry=""
tool=""
dry_run=false

usage() {
  cat <<'EOF'
Usage:
  push-runtime-images.sh --images-lock <file> --image-registry <prefix> [flags]

Flags:
  --images-lock <file>       TSV file generated by build-offline-resources.sh.
  --image-registry <prefix>  Target runtime image Registry, e.g. registry.local:5000.
  --tool <crane|skopeo>      Image copy tool. Default: auto-detect.
  --dry-run                  Print copy commands without pushing.
  -h, --help                 Show this help.

Notes:
  The target image comes from images.lock. The open-packaging metadata generator
  strips the upstream registry host so install-time image names stay short:
  registry.k8s.io/pause:3.10 -> registry.local:5000/pause:3.10
  docker.io/calico/node:v3.31.5 -> registry.local:5000/calico/node:v3.31.5
  registry.k8s.io/coredns/coredns:v1.14.2 -> registry.local:5000/coredns:v1.14.2
  Multi-architecture source images are copied for the architecture recorded in
  images.lock instead of copying the whole image index.
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

need_value() {
  [[ $# -ge 2 && -n "$2" ]] || die "$1 requires a value"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  --images-lock) need_value "$@"; images_lock="$2"; shift 2 ;;
  --image-registry) need_value "$@"; image_registry="${2%/}"; shift 2 ;;
  --tool) need_value "$@"; tool="$2"; shift 2 ;;
  --dry-run) dry_run=true; shift ;;
  -h | --help) usage; exit 0 ;;
  *) die "unknown argument: $1" ;;
  esac
done

[[ -n "$images_lock" ]] || die "--images-lock is required"
[[ -f "$images_lock" ]] || die "images lock not found: $images_lock"
[[ -n "$image_registry" ]] || die "--image-registry is required"

detect_tool() {
  if [[ "$dry_run" == true && -z "$tool" ]]; then
    echo "crane"
    return
  fi
  if [[ -n "$tool" ]]; then
    command -v "$tool" >/dev/null 2>&1 || die "$tool is required"
    echo "$tool"
    return
  fi
  if command -v crane >/dev/null 2>&1; then
    echo "crane"
    return
  fi
  if command -v skopeo >/dev/null 2>&1; then
    echo "skopeo"
    return
  fi
  die "crane or skopeo is required"
}

copy_tool="$(detect_tool)"
published=0

{
  read -r _header
  while IFS=$'\t' read -r _resource _version arch source target; do
    [[ -n "${source:-}" ]] || continue
    target="${target:-$image_registry/$source}"
    [[ -n "${arch:-}" ]] || die "missing architecture for image: $source"
    case "$copy_tool" in
    crane)
      cmd=(crane copy --platform "linux/$arch" "$source" "$target")
      ;;
    skopeo)
      cmd=(skopeo --override-os linux --override-arch "$arch" copy --multi-arch system "docker://$source" "docker://$target")
      ;;
    *)
      die "unsupported tool: $copy_tool"
      ;;
    esac
    if [[ "$dry_run" == true ]]; then
      printf 'dry-run:'
      printf ' %q' "${cmd[@]}"
      printf '\n'
    else
      echo "==> ${cmd[*]}"
      "${cmd[@]}"
    fi
    published=$((published + 1))
  done
} < "$images_lock"

echo "processed $published runtime image(s)"
